#!/bin/sh
### BEGIN INIT INFO
# Provides: Epirus block explorer
# Required-Start: $local_fs $network $named $time $syslog
# Required-Stop: $local_fs $network $named $time $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Epirus Block explorer
### END INIT INFO

NAME=epirus
USER=ubuntu
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/epirus/$NAME.log

DAEMON="/usr/local/bin/docker-compose"
ARGS="-f /home/$USER/epirus-free/docker-compose.yml -f /home/$USER/epirus-free/epirus-extensions/docker-compose-quorum.yml up"

do_start_prepare()
{
  mkdir -p `dirname $PIDFILE` || true
  mkdir -p `dirname $LOGFILE` || true
  chown -R $USER: `dirname $LOGFILE`
  chown -R $USER: `dirname $PIDFILE`
}

do_start_cmd()
{
  do_start_prepare
  echo -n "Starting daemon: "$NAME
  start-stop-daemon -C --background --start --quiet --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $ARGS>> $LOGFILE 2>&1
  echo "."
}

do_stop_cmd()
{
  echo -n "Stopping daemon: "$NAME
  start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
  rm $PIDFILE
  echo "."
}

status() {
  printf "%-50s" "Checking $NAME..."
  if [ -f $PIDFILE ]; then
    PID=$(cat $PIDFILE)
    if [ -z "$(ps axf | grep ${PID} | grep -v grep)" ]; then
      printf "%s\n" "The process appears to be dead but pidfile still exists"
    else
      echo "Running, the PID is $PID"
    fi
  else
    printf "%s\n" "Service not running"
  fi
}

case "$1" in
  start)
    do_start_cmd
    ;;
  stop)
    do_stop_cmd
    ;;
  status)
    status
    ;;
  restart)
    do_stop_cmd
    do_start_cmd
    ;;
  *)
    echo "Usage: $1 {start|stop|status|restart}"
    exit 1
esac

exit 0
